const express = require('express');
const app = express();
const port = 3000;

app.use(express.static('public'));
app.use(express.urlencoded({ extended: false }));

function htmlStart(res){
    res.write(`<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>`);
}
function htmlEnd(res){
    res.write(`
</body>
</html>`)
res.end();
}

app.get('/', async (req, res) => {
    try{
htmlStart(res);
res.write(`<h1> page generated by server </h1>`);
// res.write(`<a href = `)
let fRes = await fetch('https://rickandmortyapi.com/api/character')
let data = await fRes.json()
for(let person of data.results){
    res.write(`<h1>${person.name}</h1>`)
    let episodes = await fetch(`https://rickandmortyapi.com/api/episode`)
    let newdata = await episodes.json()
    console.log("episdode data" + newdata)
    for(let blah of newdata.results){
        if (person.url === blah.url){
        res.write(`<ul> ${blah.name} </ul>`)
        }
        else{
        }
    }
    
    }
    htmlEnd(res);
}
catch(err){
    res.write(`there was an error`+err);
}
});

app.listen(port, () => {
    console.log(`listening to u (on port ${port})`)
});
